modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/maxine-red/strawberry-twirl-companion/issues"
[[mods]]
modId="strawberrytwirl"
version="${file.jarVersion}"
displayName="Strawberry Twirl Companion"
displayURL="https://github.com/maxine-red/strawberry-twirl-companion"
logoFile="project_icon.png"
#credits=""

authors="Maxine Red"
# The description text for the mod (multi line!) (#mandatory)
description='''
A mod to add content for 'Strawberry Twirl'.

No recipes are added by this mod alone! It's meant to be used in mod packs.
'''
[[dependencies.strawberrytwirl]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.strawberrytwirl]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
