modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/maxine-red/moos-puppersized-additions/issues"
[[mods]]
modId="moospuppersizedadditions"
version="${file.jarVersion}"
displayName="Moo's Puppersized Additions"
displayURL="https://github.com/maxine-red/moos-puppersized-additions"
logoFile="project_icon.png"
#credits=""

authors="Maxine Red, Ulvra"
# The description text for the mod (multi line!) (#mandatory)
description='''
Small, vanilla friendly additions.
'''
[[dependencies.moospuppersizedadditions]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moospuppersizedadditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
